const runtimeEnv = (typeof import.meta !== 'undefined' && import.meta.env) ? import.meta.env : {};

function joinUrlPath(basePath, childPath) {
  const cleanBase = String(basePath || '/').replace(/\/+$/, '');
  const cleanChild = String(childPath || '').replace(/^\/+/, '');
  return `${cleanBase || ''}/${cleanChild}`;
}

const snapshotBaseUrl = runtimeEnv.VITE_SNAPSHOT_BASE_URL || joinUrlPath(runtimeEnv.BASE_URL || '/', 'data');

let siteManifestPromise;
let archiveCompatPromise;

export function normalizeArchivePath(relativePath) {
  let normalized = String(relativePath || '').replace(/\\/g, '/').trim();
  normalized = normalized.split('#')[0].split('?')[0];
  normalized = normalized.replace(/^https?:\/\/[^/]+/i, '');
  normalized = normalized.replace(/^\/?archive-data\/+/i, '');
  normalized = normalized.replace(/^\/+/, '');

  const reportsIndex = normalized.indexOf('reports/');
  if (reportsIndex >= 0) {
    return normalized.slice(reportsIndex);
  }

  const configIndex = normalized.indexOf('config/');
  if (configIndex >= 0) {
    return normalized.slice(configIndex);
  }

  const dataIndex = normalized.indexOf('frontend/public/data/');
  if (dataIndex >= 0) {
    return normalized.slice(dataIndex);
  }

  return normalized;
}

function buildSnapshotUrl(fileName) {
  const cleanName = String(fileName || '').replace(/^\/+/, '');
  return `${snapshotBaseUrl}/${cleanName}`;
}

async function fetchJson(url) {
  const response = await fetch(url, { cache: 'no-store' }).catch(() => null);
  if (!response || !response.ok) {
    return null;
  }
  return response.json();
}

/**
 * Load the static-site manifest. If this file exists, the app uses snapshot mode.
 */
export async function loadSiteManifest() {
  if (!siteManifestPromise) {
    siteManifestPromise = fetchJson(buildSnapshotUrl('site_manifest.json'));
  }
  return siteManifestPromise;
}

/**
 * Load the virtual archive map generated by build-frontend-snapshot.
 */
export async function loadArchiveCompatSnapshot() {
  if (!archiveCompatPromise) {
    archiveCompatPromise = (async () => {
      const manifest = await loadSiteManifest();
      if (!manifest) {
        return null;
      }
      return fetchJson(buildSnapshotUrl('archive_compat_snapshot.json'));
    })();
  }
  return archiveCompatPromise;
}

export async function isStaticSnapshotMode() {
  return Boolean(await loadSiteManifest());
}

export async function readSnapshotJson(fileName) {
  const manifest = await loadSiteManifest();
  if (!manifest) {
    return null;
  }
  return fetchJson(buildSnapshotUrl(fileName));
}

export async function readStaticArchiveJson(relativePath) {
  const archive = await loadArchiveCompatSnapshot();
  const key = normalizeArchivePath(relativePath);
  if (!archive || !archive.json_files || !Object.prototype.hasOwnProperty.call(archive.json_files, key)) {
    return { found: false, value: null };
  }
  return { found: true, value: archive.json_files[key] };
}

export async function readStaticArchiveText(relativePath) {
  const archive = await loadArchiveCompatSnapshot();
  const key = normalizeArchivePath(relativePath);
  if (!archive || !archive.text_files || !Object.prototype.hasOwnProperty.call(archive.text_files, key)) {
    return { found: false, value: null };
  }
  return { found: true, value: archive.text_files[key] };
}

export { buildSnapshotUrl };
